# Создание сообщения
POST https://marta-chat.herokuapp.com/message HTTP/1.1
Content-Type: application/json

{
  "user": "Cat",
  "message": "Meow"
}

###

# Удаление сообщения
DELETE https://marta-chat.herokuapp.com/messages/12 HTTP/1.1

